require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '11.0'

target 'sland_app' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  pod 'RNGoogleSignin', :path => '../node_modules/@react-native-google-signin/google-signin'

  # pod 'react-native-image-picker', :path => '../node_modules/react-native-image-picker'


  # pod 'react-native-image-resizer', :path => '../node_modules/react-native-image-resizer'
  

end
